#%RAML 1.0 NamedExample
value:
  -
    bookingId: 1
    name: RAHUL
    provider: OLA
    source: Mumbai
    destination: Pune
    carType: Micro
    price: 5000
    status: CONFIRMED
  -
    bookingId: 2
    name: SAMEER
    provider: OLA
    source: Nashik
    destination: Pune
    carType: Mini
    price: 4000
    status: CONFIRMED