#%RAML 1.0 Trait

responses:
  400:
    body:
      application/json:
        type: !include ../../common/dataTypes/commonErrorDataType.raml
        example: !include ../../common/examples/errorResponse400.json
  404:
    body:
      application/json:
        type: !include ../../common/dataTypes/commonErrorDataType.raml
        example: !include ../../common/examples/errorResponse404.json
  500:
    body:
      application/json:
        type: !include ../../common/dataTypes/commonErrorDataType.raml
        example: !include ../../common/examples/errorResponse500.json