#%RAML 1.0 NamedExample
value:
  -
    bookingId: 1
    name: RAHUL
    provider: OLA
    source: Mumbai
    destination: Pune
    price: 5000
    carType: Micro
    startDate: 2022/07/26
    endDate: 2022/07/27
    otp: 2355
    timestamp: 20220209_133105
  -
    bookingId: 2
    name: SAMEER
    provider: OLA
    source: Nashik
    destination: Pune
    price: 4000
    carType: Mini
    startDate: 2022/07/22
    endDate: 2022/07/23
    otp: 2355
    timestamp: 20220209_133105