#%RAML 1.0 NamedExample
value:
  bookingId: 1
  name: RAHUL
  provider: OLA
  source: Mumbai
  destination: Pune
  price: 5000
  carType: Micro
  startDate: 2017/07/26
  endDate: 2017/07/26
  otp: 2355
  timestamp: 20220209_133105